# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - antictest(stage)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b44b41cd96124a828c1aa1f30dd6558c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_762f67ea84b94f77b15fe7515e6d6af0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b44b41cd96124a828c1aa1f30dd6558c }}/staging:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'stage'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'antictest'
        slot-name: 'stage'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d14ed133f1a84fe2a082f3159d14646c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b44b41cd96124a828c1aa1f30dd6558c }}/staging:${{ github.sha }}'